services:
  dtvp:
    environment:
      DTVP_VULNERABILITY_BACKEND_IMPORT_API_KEY: ""
      DTVP_VULNERABILITY_BACKEND_IMPORT_API_KEY_FILE: /run/secrets/dtvp_vulnerability_backend_import_api_key
    secrets:
      - dtvp_vulnerability_backend_import_api_key

secrets:
  dtvp_vulnerability_backend_import_api_key:
    environment: DTVP_VULNERABILITY_BACKEND_IMPORT_API_KEY
