services:
  dtvp:
    build:
      secrets:
        - ca-certs

  agentyzer:
    build:
      secrets:
        - ca-certs

  dtvp-backup-scheduler:
    build:
      secrets:
        - ca-certs

secrets:
  ca-certs:
    file: ${DTVP_CA_CERTS_FILE}
