services:
  dtvp:
    environment:
      DTVP_DT_IMPORT_API_KEY: ""
      DTVP_DT_IMPORT_API_KEY_FILE: /run/secrets/dtvp_dt_import_api_key
    secrets:
      - dtvp_dt_import_api_key

secrets:
  dtvp_dt_import_api_key:
    environment: DTVP_DT_IMPORT_API_KEY
