services:
  demo-dependency-track-api:
    environment:
      ALPINE_DATABASE_PASSWORD: ""
      ALPINE_DATABASE_PASSWORD_FILE: /run/secrets/demo_dependency_track_database_password
    secrets:
      - demo_dependency_track_database_password

  demo-dependency-track-database:
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_PASSWORD_FILE: /run/secrets/demo_dependency_track_database_password
    secrets:
      - demo_dependency_track_database_password

  dtvp:
    environment:
      DTVP_VULNERABILITY_BACKEND_API_KEY: ""
      DTVP_VULNERABILITY_BACKEND_API_KEY_FILE: /run/secrets/dtvp_vulnerability_backend_api_key
      DTVP_VULNERABILITY_BACKEND_IMPORT_API_KEY: ""
      DTVP_VULNERABILITY_BACKEND_IMPORT_API_KEY_FILE: /run/secrets/dtvp_vulnerability_backend_import_api_key
    secrets:
      - dtvp_vulnerability_backend_import_api_key

secrets:
  demo_dependency_track_database_password:
    environment: DTVP_DEMO_DEPENDENCY_TRACK_DATABASE_PASSWORD
  dtvp_vulnerability_backend_api_key:
    environment: DTVP_DEMO_DEPENDENCY_TRACK_API_KEY
  dtvp_vulnerability_backend_import_api_key:
    environment: DTVP_DEMO_DEPENDENCY_TRACK_IMPORT_API_KEY
