INCONSISTENCY_REASON_MISSING_RESCORING_VECTOR = "MISSING_RESCORING_VECTOR"
INCONSISTENCY_REASON_ANALYSIS_STATE_MISMATCH = "ANALYSIS_STATE_MISMATCH"
INCONSISTENCY_REASON_TEAM_ASSESSMENT_MISMATCH = "TEAM_ASSESSMENT_MISMATCH"
INCONSISTENCY_REASON_ASSESSMENT_DETAILS_MISMATCH = "ASSESSMENT_DETAILS_MISMATCH"

INCONSISTENCY_REASONS = (
    INCONSISTENCY_REASON_MISSING_RESCORING_VECTOR,
    INCONSISTENCY_REASON_ANALYSIS_STATE_MISMATCH,
    INCONSISTENCY_REASON_TEAM_ASSESSMENT_MISMATCH,
    INCONSISTENCY_REASON_ASSESSMENT_DETAILS_MISMATCH,
)
